/*
 * Hypto IAM
 * APIs for Hypto IAM Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engineering@hypto.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.hypto.iam.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** SsoLoginRequest */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SsoLoginRequest {
    public static final String SERIALIZED_NAME_DOMAIN = "domain";

    @SerializedName(SERIALIZED_NAME_DOMAIN)
    private String domain;

    public static final String SERIALIZED_NAME_REDIRECT_URI = "redirectUri";

    @SerializedName(SERIALIZED_NAME_REDIRECT_URI)
    private String redirectUri;

    public static final String SERIALIZED_NAME_EMAIL = "email";

    @SerializedName(SERIALIZED_NAME_EMAIL)
    private String email;

    public SsoLoginRequest() {}

    public SsoLoginRequest domain(String domain) {

        this.domain = domain;
        return this;
    }

    /**
     * Domain of the user&#39;s organization
     *
     * @return domain
     */
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "Domain of the user's organization")
    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    public SsoLoginRequest redirectUri(String redirectUri) {

        this.redirectUri = redirectUri;
        return this;
    }

    /**
     * callback url for generating authentication url
     *
     * @return redirectUri
     */
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "callback url for generating authentication url")
    public String getRedirectUri() {
        return redirectUri;
    }

    public void setRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri;
    }

    public SsoLoginRequest email(String email) {

        this.email = email;
        return this;
    }

    /**
     * email of the user
     *
     * @return email
     */
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "email of the user")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SsoLoginRequest ssoLoginRequest = (SsoLoginRequest) o;
        return Objects.equals(this.domain, ssoLoginRequest.domain)
                && Objects.equals(this.redirectUri, ssoLoginRequest.redirectUri)
                && Objects.equals(this.email, ssoLoginRequest.email);
    }

    @Override
    public int hashCode() {
        return Objects.hash(domain, redirectUri, email);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SsoLoginRequest {\n");
        sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
        sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
